---
- name: Deploy Ansible Tower instance
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    tower_state: present
    project: tower
    iam_user: iamuser
    email: user@example.com
    region: us-east-1
    instance_type: t3.large
    boot_image: ami-123456789abcdef
    boot_disk_sizeGB: 50
    # db_disk_sizeGB: 20
    ssh_public_key: /tmp/aws_rsa.pub
    ansible_tower_version: 3.4.1-1
  tasks:
    - name: gather-subnet-facts
      register: ec2_vpc_subnet
      ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ iam_user }}-{{ project }}-subnet-0"

    - name: gather-security-group-facts
      register: ec2_secgroups
      ec2_group_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ iam_user }}-{{ project }}-public-sg"

    - name: create-ssh-keypair
      register: tower_keypair
      ec2_key:
        state: "{{ tower_state }}"
        region: "{{ region }}"
        name: "{{ iam_user }}-{{ project }}-key"
        key_material: "{{ lookup('file', ssh_public_key) }}"

    - name: create-ansible-tower-instance
      register: tower_instance
      ec2_instance:
        state: "{{ tower_state }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ boot_image }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: "{{ ec2_vpc_subnet.subnets[0].subnet_id }}"
        network:
          assign_public_ip: yes
        key_name: "{{ tower_keypair.key.name }}"
        tags:
          Name: "{{ iam_user }}-{{ project }}-tower-1"
          project: "{{ project }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_type: gp2
              volume_size: "{{ boot_disk_sizeGB }}"
              delete_on_termination: yes
          # - device_name: /dev/xvda
          #   ebs:
          #     volume_type: gp2
          #     volume_size: "{{ db_disk_sizeGB }}"
          #     delete_on_termination: yes
        security_groups:
          - "{{ ec2_secgroups.security_groups[0].group_id }}"
        user_data: |
          #!/usr/bin/env bash
          yum update -y -q
          curl -L https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ ansible_tower_version }}.tar.gz \
            -o /tmp/ansible-tower-setup-{{ ansible_tower_version }}.tar.gz
